spring:
    application:
        name: copart
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/copart}
        username: ${SPRING_DATASOURCE_USERNAME:user}
        password: ${SPRING_DATASOURCE_PASSWORD:password}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        prometheus:
            acces:
        health:
            show-details: always
minio:
    url: ${MINIO_ENDPOINT:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:admin}
    secret-key: ${MINIO_SECRET_KEY:admin123}
    bucket: image




